### ISSUE TITLE
More images

### ISSUE THREAD

**Issue by andymartinwork** [IdeaSpaceVR/aframe-360-degree-photosphere#1]
Hi, I really love your photoshere viewer and I'm adding it as a link on my app.

Is it possible that you can add all of the photos to the little viewer? Perhaps in a 3 x 3 layout?

I'm simulating touches on the screen to bring up the menu using the magnet button, not using the spacebar by the way.

**Comment by weddingdj** [comment]
Thanks for the comment!

I am planning to add a "scroll link" to it, so you can go down and up in the list. I believe showing 3 thumbnail images at a time is good, a 3 x 3 layout puts some unnecessary strain to the person I think.

The component is listening for touch events as well: view-source:https://www.ideaspacevr.org/examples/aframe/aframe-360-degree-photosphere/js/components/isvr_photosphere_menu.js - a-frame is not cardboard compatible yet, it doesn't work on a Nexus 5. How do you simulate touch events?

**Comment by andymartinwork** [comment]
Sorry I didn't reply, it looks like I still had a github filter active from my last job!

I simulate touch events by using a touchdown or touchstart and touchup or touchend.

a-frame is not cardboard compatible but my browser is!

https://play.google.com/store/apps/details?id=com.vrambling.vrambling

**Comment by weddingdj** [comment]
a-frame is Cardboard compatible, I use it with Chrome on my Nexus phone. I am talking about the Cardboard viewer, not the API.
