### ISSUE TITLE
View-source in VR mode isn't necessary

### ISSUE THREAD

**Issue by andymartinwork** [IdeaSpaceVR/aframe-360-degree-photosphere#2]
It's only on one of the screens, and looks very bad in VR.

**Comment by weddingdj** [comment]
I don't see the view-source link in VR mode, only in desktop mode. I tested in Firefox Nightly.

**Comment by cvan** [comment]
I see it [here](https://github.com/IdeaSpaceVR/aframe-360-degree-photosphere/blob/9f5774/index.php#L31).

I would add this style:

``` css
.view-source:fullscreen {
  display: none;
}
```

In the future, we'll have events so you know when you're truly in "VR Mode" (not just assuming that if we're in Fullscreen that we're also in VR Mode).

**Comment by weddingdj** [comment]
Sure, will do, but I would not see the View Source when in VR mode.

**Comment by cvan** [comment]
> Sure, will do, but I would not see the View Source when in VR mode.

in VR mode, you re-create the link using A-Frame (with an `<a-entity>`, for example). otherwise, it won't be clickable anyway. (and in Chrome the link won't be visible at all because Chrome fullscreens the `<canvas>` not the entire page.)

**Comment by weddingdj** [comment]
The view source link was supposed to be visible when not being in fullscreen or VR mode, just when someone lands on the page. I added it to let people easily view the source code, like you do in your a-frame examples.
