### ISSUE TITLE
Change index.php to index.html

### ISSUE THREAD

**Issue by cvan** [IdeaSpaceVR/aframe-360-degree-photosphere#4]
I assume this is because your server is configured to serve PHP pages. But is it possible to change this?

**Comment by weddingdj** [comment]
What is the reason? I assume you mean it could be confusing to newbies that they might think they need php in order to run a-frame?

**Comment by weddingdj** [comment]
I changed it to index.html

**Comment by cvan** [comment]
> What is the reason? I assume you mean it could be confusing to newbies that they might think they need php in order to run a-frame?

Yep, that's why. GitHub Pages doesn't support PHP is one reason. And there don't seem to be any PHP code in the file anyway.

**Comment by weddingdj** [comment]
Thanks for clarification.
