### ISSUE TITLE
photosphere changes the background even when the cursor is invisible

### ISSUE THREAD

**Issue by SantanMaddi** [IdeaSpaceVR/aframe-360-degree-photosphere#6]
Although the cursor is invisible and when pointed it to the one of the pictures in the menu, the photosphere background is changed. A very minor bug, thought of letting you know.

**Comment by weddingdj** [comment]
Thanks! I look into that.

**Comment by SantanMaddi** [comment]
One possible solution is, inside onclick bound function

```
if(this.el.parentEl.getAttribute('visible')){
   //change the photosphere material
}
```

Let me give a PR to this.

**Comment by weddingdj** [comment]
Thanks!
