### ISSUE TITLE
Down arrow not working on my end

### ISSUE THREAD

**Issue by askwpcoach** [IdeaSpaceVR/aframe-360-degree-photosphere#9]
Hello,

I love your menu and would like to learn from it so I've been trying to get it setup on my server.

**Problem I'm having:**
The 1st 3 thumbnails load perfectly, but when I click the down arrow no images load. When I inspect, I can see there is a 404 on the JSON endpoint (paginated). 

http://scriptstrainer.com/vr/slideshow/

Please explain "field-data" and how I should make adjustments.

Kind Regards,

**Comment by weddingdj** [comment]
Hello,

the field data JSON endpoint is served by IdeaSpace which you would need to install on your server. Or for demo purposes you have to add the JSON endpoint URL from the example 360 degree photosphere page.

**Comment by askwpcoach** [comment]
Hello,

Thank you for this information. I will install IdeaSpace now.
